from django.db import models
class Data(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()
    unique_squirrel_id = models.CharField(unique=True, max_length=200)
    shift = models.CharField(max_length=200, blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    age = models.CharField(max_length=200, blank=True, null=True)
    primary_fur_color = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    running = models.BooleanField(blank=True, null=True)
    chasing = models.BooleanField(blank=True, null=True)
    climbing = models.BooleanField(blank=True, null=True)
    eating = models.BooleanField(blank=True, null=True)
    foraging = models.BooleanField(blank=True, null=True)
    specific_location=models.CharField(max_length=200, null=True, blank=True)
    other_activities=models.CharField(max_length=200, null=True, blank=True)
    kuks=models.BooleanField(null=True, blank=True)
    quaas=models.BooleanField(null=True, blank=True)
    moans=models.BooleanField(null=True, blank=True)
    tail_flags=models.BooleanField(null=True, blank=True)
    tail_twitches=models.BooleanField(null=True, blank=True)
    approaches=models.BooleanField(null=True, blank=True)
    indifferent=models.BooleanField(null=True, blank=True)
    runs_from=models.BooleanField(null=True, blank=True)
